<?php
require_once 'Huxley-php/Huxley.php';
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
<?php
// generated by http://restunited.com
// for any feedback/issue with the code, please send to support{at}restunited.com

// setup authentication
$access_token = "e142346d-3e38-465e-94e6-29fb84d8baa3";
$id = "GLY";

try {
    $api_client = new Huxley\APIClient('https://remus-rail.azurewebsites.net');
    $arrivals_api = new Huxley\ArrivalsAPI($api_client);
    $response = $arrivals_api->getArrivalsBoard($access_token, $id);
    var_dump($response);
} catch (Exception $e) {
    echo 'Caught exception: ', $e->getMessage(), "\n";
}
?>
</body>
</html>