<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

/**
 * source code generated by http://restunited.com using Swagger Codegen
 * for any feedback/issue, please send to feedback{at}restunited.com
 *
 * swagger-codegen: https://github.com/wordnik/swagger-codegen
 */

/**
 * APIClient.php
 */

namespace Huxley\models;

class DestinationField {

  static $swaggerTypes = array(
      'assocIsCancelledField' => 'bool',
      'crsField' => 'string',
      'futureChangeToField' => 'string',
      'locationNameField' => 'string',
      '_PropertyChanged' => 'string',
      'viaField' => 'string'

    );

  /**
  * Associscancelledfield
  */
  public $assocIsCancelledField; // bool
  /**
  * Crsfield
  */
  public $crsField; // string
  /**
  * Futurechangetofield
  */
  public $futureChangeToField; // string
  /**
  * Locationnamefield
  */
  public $locationNameField; // string
  /**
  * Propertychanged
  */
  public $_PropertyChanged; // string
  /**
  * Viafield
  */
  public $viaField; // string
  }

