<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

/**
 * source code generated by http://restunited.com using Swagger Codegen
 * for any feedback/issue, please send to feedback{at}restunited.com
 *
 * swagger-codegen: https://github.com/wordnik/swagger-codegen
 */

/**
 * APIClient.php
 */

namespace Huxley\models;

class GetDepartureBoard {

  static $swaggerTypes = array(
      'areServicesAvailableField' => 'bool',
      'busServicesField' => 'string',
      'crsField' => 'string',
      'ferryServicesField' => 'string',
      'filtercrsField' => 'string',
      'filterLocationNameField' => 'string',
      'filterTypeField' => 'int',
      'generatedAtField' => 'DateTime',
      'locationNameField' => 'string',
      'nrccMessagesField' => 'array[NrccMessagesField]',
      'platformAvailableField' => 'bool',
      '_PropertyChanged' => 'string',
      'trainServicesField' => 'array[TrainServicesField]'

    );

  /**
  * Areservicesavailablefield
  */
  public $areServicesAvailableField; // bool
  /**
  * Busservicesfield
  */
  public $busServicesField; // string
  /**
  * Crsfield
  */
  public $crsField; // string
  /**
  * Ferryservicesfield
  */
  public $ferryServicesField; // string
  /**
  * Filtercrsfield
  */
  public $filtercrsField; // string
  /**
  * Filterlocationnamefield
  */
  public $filterLocationNameField; // string
  /**
  * Filtertypefield
  */
  public $filterTypeField; // int
  /**
  * Generatedatfield
  */
  public $generatedAtField; // DateTime
  /**
  * Locationnamefield
  */
  public $locationNameField; // string
  /**
  * Nrccmessagesfield
  */
  public $nrccMessagesField; // array[NrccMessagesField]
  /**
  * Platformavailablefield
  */
  public $platformAvailableField; // bool
  /**
  * Propertychanged
  */
  public $_PropertyChanged; // string
  /**
  * Trainservicesfield
  */
  public $trainServicesField; // array[TrainServicesField]
  }

