<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

/**
 * source code generated by http://restunited.com using Swagger Codegen
 * for any feedback/issue, please send to feedback{at}restunited.com
 *
 * swagger-codegen: https://github.com/wordnik/swagger-codegen
 */

/**
 * APIClient.php
 */

namespace Huxley\models;

class TrainServicesField {

  static $swaggerTypes = array(
      'adhocAlertsField' => 'string',
      'currentDestinationsField' => 'string',
      'currentOriginsField' => 'string',
      'destinationField' => 'array[DestinationField]',
      'etaField' => 'string',
      'etdField' => 'string',
      'isCircularRouteField' => 'bool',
      'operatorCodeField' => 'string',
      'operatorField' => 'string',
      'originField' => 'array[OriginField]',
      'platformField' => 'string',
      '_PropertyChanged' => 'string',
      'serviceIDField' => 'string',
      'staField' => 'string',
      'stdField' => 'string'

    );

  /**
  * Adhocalertsfield
  */
  public $adhocAlertsField; // string
  /**
  * Currentdestinationsfield
  */
  public $currentDestinationsField; // string
  /**
  * Currentoriginsfield
  */
  public $currentOriginsField; // string
  /**
  * Destinationfield
  */
  public $destinationField; // array[DestinationField]
  /**
  * Etafield
  */
  public $etaField; // string
  /**
  * Etdfield
  */
  public $etdField; // string
  /**
  * Iscircularroutefield
  */
  public $isCircularRouteField; // bool
  /**
  * Operatorcodefield
  */
  public $operatorCodeField; // string
  /**
  * Operatorfield
  */
  public $operatorField; // string
  /**
  * Originfield
  */
  public $originField; // array[OriginField]
  /**
  * Platformfield
  */
  public $platformField; // string
  /**
  * Propertychanged
  */
  public $_PropertyChanged; // string
  /**
  * Serviceidfield
  */
  public $serviceIDField; // string
  /**
  * Stafield
  */
  public $staField; // string
  /**
  * Stdfield
  */
  public $stdField; // string
  }

